#!/usr/bin/env escript
%% -*- erlang -*-
%%! erl -pa ebin/

main([ConfigFilePath, OutputFilePath]) ->
	main_aux(ConfigFilePath, OutputFilePath);	
main(_) ->
	main_aux(".config", "runlog.txt").
    
main_aux(ConfigFilePath, OutputFilePath) ->
    try
    	error_logger:logfile({open, OutputFilePath}),
        runner:main(ConfigFilePath,parallel),
        error_logger:logfile(close)
    catch
    	TypeOfError:ErrorValue ->  io:format("\Exception ~w ~w, stacktrace: ~w \n",
    		[TypeOfError, ErrorValue, erlang:get_stacktrace()])	
    end.


